require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - html2rss.gemspec

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Layout/ClassStructure:
  Enabled: true

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/LineLength:
  Max: 110

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/NumberConversion:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true


Performance/CaseWhenSplat:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/OpenStruct:
  Enabled: true


RSpec/NestedGroups:
  Exclude:
    - spec/html2rss_spec.rb


Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - '**/*_spec.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ConstantVisibility:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/Documentation:
  Exclude:
    - lib/html2rss/version.rb

Style/DocumentationMethod:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/IpAddresses:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MissingElse:
  Enabled: true

Style/MultilineMethodSignature:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/StderrPuts:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
