require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - html2rss.gemspec

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 15

Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - '**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Description: 'Enforce braces style around hash parameters.'
  Enabled: true

Style/HashSyntax:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

RSpec/NestedGroups:
  Exclude:
    - spec/html2rss_spec.rb
