require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable

Metrics/AbcSize:
  Max: 17.23

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - html2rss.gemspec

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Layout/LineLength:
  Max: 110

RSpec/NestedGroups:
  Exclude:
    - spec/html2rss_spec.rb
Style/Documentation:
  Exclude:
    - lib/html2rss/version.rb

Style/DocumentationMethod:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 9

Style/AsciiComments:
  AllowedChars:
    - €

Style/FormatStringToken:
  Exclude:
    - spec/html2rss/attribute_post_processors/template_spec.rb
