require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - html2rss.gemspec

Layout/LineLength:
  Max: 110

RSpec/NestedGroups:
  Exclude:
    - spec/html2rss_spec.rb

RSpec/MultipleMemoizedHelpers:
  Max: 9

Style/AsciiComments:
  AllowedChars:
    - €

Style/FormatStringToken:
  Exclude:
    - spec/html2rss/attribute_post_processors/template_spec.rb
