sudo: false
language: ruby

before_install:
  - gem update --system
  - gem install bundler
bundler_args: --jobs=3 --retry=3

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.1.17.0
  - jruby-9.2.0.0

script:
  - bundle exec rspec
