# This config is for demonstration only.
---
headers:
  'User-Agent': "Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1"
feeds:
  json:
    channel:
      title: JSON
      url: https://api.cinemascore.com/guest/surveys
      ttl: 600
      json: true
    selectors:
      items:
        selector: 'new > new, recent > recent'
      title:
        selector: 'title'
        post_process:
          name: 'template'
          string: '%s (%s) [Rated %s] (%s)'
          methods:
            - self
            - grade
            - mpaa_rating
            - year
      grade:
        selector: 'grade'
      movie_title:
        selector: 'movie-title'
      link:
        post_process:
          name: 'template'
          string: 'https://www.metacritic.com/search/movie/%s/results'
          methods:
            - movie_title
      mpaa_rating:
        selector: 'mpaa-rating'
      distributor:
        selector: 'distributor'
      year:
        selector: 'year'
      categories:
        - mpaa_rating
        - grade
        - year
